services:
  db-dev:
    image: postgres:18-alpine
    container_name: flightdb-dev
    ports: ["127.0.0.1:${DB_PORT}:5432"]
    env_file:
      - ./.dev.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_dev:
