spring:
  profiles:
    active: dev
  application:
    name: Flight Data App
    description: This application provides a REST API for managing flight data, demonstrating a typical CRUD architecture built with Spring Boot and Java 21.
    author:
      name: Giovanne D.
      contact: giojo.dev@outlook.com
    external-link: https://github.com/GioDalalibera/flight-data-app
    current-version: v1
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      "[hibernate.jdbc.time_zone]": UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
logging:
  level:
    # Enable verbose libs only when needed:
    root: INFO
    "[com.giojo.flightdata]": INFO
    "[org.springframework.web]": WARN
    "[com.zaxxer.hikari]": WARN
    "[org.hibernate.SQL]": WARN
    "[org.hibernate.type.descriptor.sql.BasicBinder]": OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 200MB

#OpenAPI docs and Swagger, disabled by default.
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

crazy-supplier:
  base-url: "https://api.crazy-supplier.com"
