spring:
  datasource:
    url: jdbc:h2:mem:flightdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.hibernate.SQL: warn
